spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "GMT+8"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: groupId
      auto-offset-reset: earliest
  cassandra:
    keyspace-name: test
    schema-action: create_if_not_exists
    contact-points: cassandra
    local-datacenter: datacenter1
    port: 9042
    create-keyspace: true